site_name: ASMPT Virtual Assist
theme:
  name: material
  language: en
  palette:
    primary: red
    accent: red
  logo: logo.png
  favicon: icon.png
  extra:
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Deutsch
        link: /de/
        lang: de
      - name: 中文
        link: /zh/
        lang: zh
  features:
    - navigation.indexes
    - navigation.sections
    - toc.follow 
plugins:
  - search
  - glightbox
  - tags:
      tags_extra_files:
        compatibility.md:
          - compat 
        web.md:
          - html
          - js
          - css    
        gtag:
          - G-ZWQCQKMBGJ  
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
        zh: 中文
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - attr_list
  - toc:
      permalink: ⚓︎
      permalink_title: Permalink
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Intro: "index.md"
  - "FAQ": "faqs.md"
  - "Updates": "updates"

  - Getting Started:
      - "Virtual Assist App (Mobile)": "Getting Started/quick-start-guide-assistant.md"
      - "Virtual Assist Web (Web)": "Getting Started/quick-start-guide-cs.md"
      - "Features/answers.md"
      - "Features/linksharing.md"
  - Virtual Assist Web Features:
      - "Features/insights.md"
      - "Features/search.md"
      - "Features/tutorials.md"
      - "Features/documents.md"
      - "Features/articles.md"
      - "Features/adminpanel.md"
  - Virtual Assist App Features:
      - "Features/documents_na.md"
      - "Features/logbook.md"
      - "Features/supportscreen.md"
      - "Features/pushnotifications.md"

  - Admin:

      - Security and Access:
          - "Admin Documentation/Security and Access/product_access_groups.md"
          - "Admin Documentation/Security and Access/roles_and_permissions.md"
          - "Admin Documentation/Security and Access/data_security_and_privacy.en.md"
copyright: Copyright &copy; 2023 @ ASMPT Virtual Assist GmbH - <a href="#__consent">Change cookie settings</a>
extra:
  consent:
    title: Cookie consent
    description: >- 
      Our website uses cookies, which are small text files, 
      to distinguish you from other users and provide you 
      with a good experience when you browse our website. 
      You can allow all or manage them individually.
      You can find further details of our cookies here:
      <a href="https://smt.asmpt.com/en/products/software-solutions/virtual-assist/privacy-policy">Privacy policy</a>
    actions:
      - accept
      - reject
      - manage
    cookies:
      Imgur: Imgur
    
  social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/knowron/
          name: ASMPT Virtual Assist on LinkedIn
        - icon: fontawesome/solid/envelope
          link: mailto:<asm-support.df@asmpt.com>
  
  analytics:
      provider: google
      property: G-ZWQCQKMBGJ




