name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install mkdocs-material==8.5.11
      - run: pip install mkdocs-static-i18n==0.53
      - run: pip install mkdocs-glightbox==0.3.1
      - run: mkdocs gh-deploy --force
